#@ load("@ytt:data", "data")
---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

fqdn: #@ "db.{}".format(data.values.domain)

users:
- name: crdant
  gecos: "Chuck D'Antonio"
  groups:
  - users 
  - adm 
  - sudo
  ssh_authorized_keys: #@ data.values.ssh.authorized_keys.crdant
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  lock_passwd: true

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## 
apt:
  preserve_sources_list: true
  sources:
    microsoft:
      source: #@ data.values.microsoft.mssql_list 
      key: #@ data.values.microsoft.pgp_key
    mssql:
      source: #@ data.values.microsoft.prod_list 
      key: #@ data.values.microsoft.pgp_key

## Install additional packages on first boot
packages:
- ca-certificates
- curl
- zsh
- direnv
- neovim
- mssql-server
- mssql-tools
- unixodbc-dev
- msodbcsql17

## write the systemd service file and coredns config
## files
write_files: 
- path: /etc/profile.d/mssql-tools.sh
  content: |
    export PATH="$PATH:/opt/mssql-tools/bin"
 
### Run arbitrary commands at rc.local like time
runcmd:
- [ chsh, -s, /usr/bin/zsh, crdant ]
